# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='letter',
            name='title',
            field=models.CharField(default='tmp', max_length=200),
            preserve_default=False,
        ),
    ]
