# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171207_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='institute_sponsored',
        ),
        migrations.AddField(
            model_name='ongoinguserinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
