# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180119_0934'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='child',
            managers=[
                ('objects', main.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='donor',
            managers=[
                ('objects', main.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='volunteer',
            managers=[
                ('objects', main.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='letter',
            name='verified',
            field=models.NullBooleanField(default=None),
        ),
    ]
