# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180119_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Child', unique=True),
        ),
    ]
